name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Checks, build, and run tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.92
          components: rustfmt, llvm-tools-preview, clippy

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Install Tools
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-deny, cargo-nextest, cargo-llvm-cov

      - name: Run rustfmt 
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --all-targets -- -D warnings

      - name: Cargo deny check
        run: cargo deny check advisories

      - name: Run tests
        run: cargo nextest run

      - name: Run coverage and enforce threshold
        run: cargo llvm-cov nextest --fail-under-lines 90